spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
          #search-locations: "classpath:/config"
        #search-locations: file:///C:/Users/ayafo/IntelliJ_workspace/aya-spring-cloud/config-repo
        git:
          uri: https://github.com/ayafounes/config-repo.git
          default-label: main
          clone-on-start: true
server:
  port: 9999